<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pmmoviebase"
 *
 * Auto generated by Extension Builder 2015-06-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'MovieDatabase',
    'description' => 'Shows your movie library',
    'category' => 'plugin',
    'author' => '@pmnewmedia.com',
    'author_email' => 'moviedatabase@pm-newmedia.com',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.1',
    'constraints' =>
        array(
            'depends' =>
                array(
                    'bootstrap_package' => '6.2.16-8.6.99',
                    'extbase' => '6.2.0-8.99.99',
                    'fluid' => '6.2.0-8.99.99',
                    'typo3' => '6.2.0-8.99.99',
                ),
            'conflicts' =>
                array(),
            'suggests' =>
                array(),
        ),
    'clearcacheonload' => true
);